"""
Remember Forward - LEXICON DOMAIN LIST
The table of contents for the whole eye-readable pictorial lexicon.

Structure follows the Oxford-Duden Pictorial model (28,000 entries on 384 plates,
~73 terms per plate) but runs deliberately LIGHTER - ~65 words per plate - to keep
everything readable by the naked eye at 8pt / ~2mm cap height.

77 plates x ~65 words = ~5,005 words.
Two-sided in the settled 120x170mm format = 39 physical plates.

PLATE GRAMMARS - not everything is a scene. The abstract residue needs its own forms.
  SCENE    a place, with people and things in it, numbered callouts into the picture
  SEQUENCE a process over time, numbered panels left-to-right
  DIAGRAM  an abstract system drawn as structure (kinship, number, calendar)
  ARRAY    meaning carried by CONTRAST - paired opposites side by side
  ANATOMY  labelled whole, the special case of a body or object dissected

Every plate: numbered callouts on the picture, words in a swappable margin strip.
Change the language, re-etch the strip only. The scene itself is language-free.

TIER: 0 = NSM semantic primes (~65)   1 = core ~1000   2 = out to 5000
"""

SECTIONS = [
    ("A", "FOUNDATION", "How to read the system, and the words everything else is defined in."),
    ("B", "BODY & LIFE", "The one referent every human finder shares."),
    ("C", "IMMEDIATE SURVIVAL", "The first week. Nothing here can wait."),
    ("D", "HEALTH", "Staying alive past the first week."),
    ("E", "FOOD", "Getting it, keeping it, not being poisoned by it."),
    ("F", "AGRICULTURE", "The shift from finding food to making it."),
    ("G", "MATERIALS & MAKING", "Turning the world into things. The rebuild spine."),
    ("H", "TOOLS & TECHNOLOGY", "Force, motion, and the machines that multiply them."),
    ("I", "MEASURE, TIME & PLACE", "Knowing where and when you are."),
    ("J", "SOCIETY & GOVERNANCE", "Living together without it going wrong."),
    ("K", "LANGUAGE & MIND", "Speech, record, teaching, inner life."),
    ("L", "ABSTRACT RESIDUE", "The words no scene can hold. Contrast does the work instead."),
]

# id, section, title, grammar, words, tier, depiction, sample callouts, links
PLATES = [
 # ---------------------------------------------------------------- A FOUNDATION
 ("A01","A","How To Read These Plates","DIAGRAM",40,0,
  "The key to the whole system. A callout number pointing into a picture, then the same number in the margin strip beside a word. Arrow = direction. Panel border = one moment. Row of panels = time passing. Hand = do this. Crossed panel = the result went badly.",
  ["number","word","picture","arrow","step","before","after","same","this one","look"],
  "Replaces plate00 master key. Build FIRST and functional-test it."),
 ("A02","A","Person, Body, Being","SCENE",55,0,
  "Several people of different ages and builds standing together, one pointing at self, one pointing at another. Establishes I / you / someone before anything else can be said.",
  ["I","you","someone","people","body","person","self","other","one","many","alive"],
  "NSM primes. Anchors every later plate."),
 ("A03","A","Doing, Moving, Happening","SEQUENCE",55,0,
  "Panel pairs: a figure at rest then acting; a stone still then falling; a hand touching then holding. The verb primes shown as change between two panels.",
  ["do","happen","move","touch","hold","make","stop","start","go","come"],
  "NSM primes."),
 ("A04","A","Saying, Thinking, Knowing, Feeling","SCENE",55,0,
  "Two people talking, with a speech mark from one mouth; a third figure with a thought enclosure above the head containing a small picture of the thing thought about.",
  ["say","word","think","know","want","feel","see","hear","true","not know"],
  "NSM primes. The thought-enclosure convention is used on every later plate."),
 ("A05","A","Number & Counting","DIAGRAM",50,1,
  "Mayan dot-bar-shell base 20 laid against tally marks and against counted objects, so the notation is taught by direct correspondence rather than assumed.",
  ["one","two","five","ten","twenty","zero","many","few","all","none","count","add"],
  "Mayan system already settled. Cross-ref plate01 Rosetta index."),

 # ---------------------------------------------------------------- B BODY & LIFE
 ("B01","B","The Body Outside","ANATOMY",70,1,
  "A standing figure, front and back, callouts to every external part. The single most translatable plate in the set - every finder has the referent in hand.",
  ["head","eye","ear","mouth","tooth","neck","arm","hand","finger","chest","back","leg","foot","skin","hair","blood"],""),
 ("B02","B","The Body Inside","ANATOMY",60,2,
  "Cutaway torso and head: skeleton, heart, lungs, gut, brain. Drawn as cross-section because it is the only view that reveals hidden structure.",
  ["bone","skull","rib","heart","lung","stomach","gut","liver","brain","nerve","muscle","vein"],
  "Supports D-series first aid and injury plates."),
 ("B03","B","The Ages Of A Life","SEQUENCE",45,1,
  "Left to right: newborn, child, youth, adult, elder, and the body at death. One continuous figure aging across the panels.",
  ["baby","child","boy","girl","youth","adult","old","elder","grow","age","live","die"],""),
 ("B04","B","Kinship","DIAGRAM",60,1,
  "A family tree with figures rather than boxes, three generations, marriage links and descent links drawn differently. Ego marked with the 'I' sign from A02.",
  ["mother","father","child","son","daughter","sister","brother","grandmother","aunt","cousin","husband","wife","family"],
  "Kinship terms vary enormously between cultures - depict the RELATION, let the strip name it."),
 ("B05","B","Birth","SEQUENCE",55,2,
  "Pregnancy, labour positions, the attendant's hands, cutting and tying the cord, the newborn warmed against the mother. Consequence strip first: what goes wrong when hands are unwashed.",
  ["pregnant","womb","born","labour","push","cord","tie","cut","afterbirth","warm","first milk","midwife"],
  "Audit flagged first aid/medical as a missing topic. This is the highest-stakes plate in the set."),
 ("B06","B","Death & The Dead","SCENE",40,1,
  "Burial, cairn, pyre, and a grave marker being made - shown as several practices side by side, none privileged, because this is where cultural assumption is most dangerous.",
  ["die","dead","body","bury","grave","burn","mourn","remember","mark","name"],
  "Ties to the surface-marker thread."),

 # ---------------------------------------------------------------- C SURVIVAL
 ("C01","C","Finding Water","SCENE",60,1,
  "A landscape read for water: valley bottom, green vegetation band, animal trail converging, seep at a rock base, dew collection. Bad sources marked by consequence panel, not by a crossed circle.",
  ["water","river","stream","spring","well","rain","dew","seep","pool","dig","carry","thirst"],
  "Wavy horizontal lines = water throughout. Never a teardrop."),
 ("C02","C","Making Water Safe","SEQUENCE",55,1,
  "Consequence strip first - drinking bad water, then sickness. Then: cloth pre-filter, sand-charcoal-gravel column, rolling boil, cooled and covered storage.",
  ["dirty","clean","filter","sand","gravel","charcoal","cloth","boil","cool","cover","safe","sick"],
  "Existing plate02 / plate02_filter_review. Reuse the cross-section material symbols."),
 ("C03","C","Making Fire","SEQUENCE",55,1,
  "Bow drill and hand drill in side elevation with the hand-tool relationship clear; tinder nest, ember transfer, feeding up from tinder to kindling to fuel.",
  ["fire","spark","ember","tinder","kindling","fuel","smoke","flame","blow","dry","hot","burn"],""),
 ("C04","C","Keeping & Using Fire","SCENE",50,1,
  "A hearth in use: banking for the night, carrying an ember, cooking position, drying rack, smoke management inside a shelter, and what an unattended fire does.",
  ["hearth","bank","carry","ash","coal","cook","dry","smoke","vent","spread","put out"],""),
 ("C05","C","Shelter Now","SEQUENCE",55,1,
  "Overnight shelter from what is at hand: debris hut, lean-to, snow trench, rock overhang. Built in sequence, with the insulating layer thickness made explicit.",
  ["shelter","roof","wall","branch","leaf","bark","snow","insulate","ground","bed","wind","dry"],""),
 ("C06","C","Shelter To Last","SCENE",65,2,
  "Construction cutaway: foundation, post and beam, wattle and daub, thatch and shingle roofing, a smoke hole, a door. Cross-section so the wall's inside is visible.",
  ["post","beam","frame","wall","daub","thatch","shingle","floor","door","window","chimney","foundation"],""),
 ("C07","C","Cold, Heat & Weather","ARRAY",50,1,
  "Paired panels: the body losing heat vs holding it; layered clothing vs soaked clothing; shade and water vs sun exposure. Frostbite and heat collapse shown as consequence, drawn on the body.",
  ["cold","hot","wet","dry","wind","shade","sweat","shiver","freeze","layer","warm","cool"],""),
 ("C08","C","Danger","SCENE",55,1,
  "A landscape with real hazards depicted in their settings: thin ice, undercut bank, rockfall, a defensive animal with young, a snake's posture, deep mud, standing dead timber.",
  ["danger","careful","fall","deep","sharp","poison","bite","sting","animal","warn","avoid","safe"],
  "NO skulls, no circle-slash. Hazard must be shown by situation and consequence."),

 # ---------------------------------------------------------------- D HEALTH
 ("D01","D","Wounds & Bleeding","SEQUENCE",55,2,
  "Direct pressure, elevation, packing, binding. A deep wound cleaned with boiled cooled water. Consequence panels for a wound left dirty over several days.",
  ["cut","wound","bleed","press","bind","bandage","clean","stitch","swell","pus","heal","scar"],""),
 ("D02","D","Bones & Burns","SEQUENCE",50,2,
  "Splinting a limb, immobilising, slinging. Burn treatment by cooling with water and covering. Shown in side elevation so the hand-to-limb relationship is unambiguous.",
  ["bone","break","splint","bind","sling","rest","burn","cool","blister","cover","pain","carry"],""),
 ("D03","D","Signs Of Sickness","ARRAY",55,2,
  "A well body beside a sick one, repeated for each sign: fever shown by sweat and shiver, dehydration by skin and eye, breathing difficulty by posture, infection by the wound's edge.",
  ["sick","fever","cough","weak","thirsty","vomit","loose stool","rash","swollen","breath","pain","rest"],""),
 ("D04","D","Clean Living","SCENE",55,1,
  "A settlement laid out correctly: latrine sited downhill and away from the well, handwashing at the food place, refuse pit, sick person separated. The single highest-value plate for mortality.",
  ["wash","hands","soap","ash","latrine","dig","cover","waste","flies","water","distance","apart"],
  "Cross-check OCHA WASH icons before drawing."),
 ("D05","D","Plants That Heal","DIAGRAM",60,2,
  "Plant portraits with the used part called out, plus preparation: infusion, decoction, poultice, salve. Deliberately conservative - only widely distributed genera.",
  ["leaf","root","bark","flower","steep","boil","crush","poultice","salve","dose","strong","weak"],
  "RISK: species distribution changes over millennia. Prefer preparation METHOD over species ID."),

 # ---------------------------------------------------------------- E FOOD
 ("E01","E","What Can Be Eaten","SEQUENCE",60,1,
  "The universal edibility test as a numbered sequence with waiting periods drawn as sun positions. Contact, lip, tongue, small taste, wait, swallow, wait.",
  ["eat","taste","wait","spit","poison","safe","bitter","milky","smell","test","little","sick"],""),
 ("E02","E","Gathering","SCENE",65,2,
  "A foraging landscape by layer: nuts and fruit above, berries and greens at hand height, roots and tubers below ground shown in cutaway.",
  ["fruit","nut","seed","berry","leaf","root","tuber","mushroom","ripe","pick","dig","basket"],""),
 ("E03","E","Hunting & Trapping","SCENE",60,2,
  "Snare, deadfall, pit and net drawn in the setting where each is placed, with the trigger mechanism enlarged. Tracks and sign along the trail.",
  ["hunt","track","sign","trap","snare","bait","spear","bow","arrow","net","catch","kill"],""),
 ("E04","E","Fishing","SCENE",55,2,
  "Line and hook, fish trap, weir, spear, net. A river cross-section showing where fish hold, which is the part that actually transfers.",
  ["fish","hook","line","bait","net","trap","weir","spear","river","deep","shallow","catch"],""),
 ("E05","E","Butchering","SEQUENCE",55,2,
  "Bleeding, skinning, opening, jointing, and separating what is kept: meat, fat, organs, hide, sinew, bone, gut. Nothing discarded without being named.",
  ["cut","skin","hide","joint","meat","fat","organ","sinew","bone","gut","blood","clean"],
  "Feeds G04 hides and G01 cordage - sinew is a material, not waste."),
 ("E06","E","Cooking","SCENE",60,1,
  "A hearth with the methods around it: roasting, boiling in a pot, stone boiling in a skin, baking in ashes, an earth oven in cutaway.",
  ["cook","roast","boil","bake","pot","stone","ash","oven","stir","raw","done","burn"],""),
 ("E07","E","Keeping Food","SEQUENCE",60,2,
  "Drying rack, smoke house in cutaway, salting in a vessel, fermenting crock with the gas escape, cold storage in a pit.",
  ["dry","smoke","salt","ferment","cool","store","jar","crock","seal","brine","sour","keep"],""),
 ("E08","E","Spoiled & Safe","ARRAY",45,1,
  "Good food beside the same food spoiled, repeated across types: meat, grain, milk, fruit. Mould, smell, slime, swelling shown directly.",
  ["fresh","old","rot","mould","smell","slime","swell","throw away","safe","sick","cover","cold"],
  "Audit flagged food safety as missing."),

 # ---------------------------------------------------------------- F AGRICULTURE
 ("F01","F","Soil","ANATOMY",55,2,
  "Soil profile in cross-section: litter, topsoil, subsoil, parent rock. Beside it a compost heap in cutaway and a charcoal-amended dark earth bed.",
  ["soil","earth","sand","clay","loam","dark","compost","rot","dung","worm","fertile","poor"],
  "Terra preta is in the idea backlog - this is where it lands."),
 ("F02","F","Seeds","SEQUENCE",55,2,
  "Seed saving through the year: selecting the best plant, drying, cleaning, storing dry and cool, and a germination test on a damp cloth.",
  ["seed","save","select","dry","clean","store","cool","sprout","test","viable","old","plant"],""),
 ("F03","F","Planting","SEQUENCE",60,2,
  "Ground broken, rows set, spacing shown against a hand span, depth in cutaway, thinning, weeding, and companion planting drawn as a bed layout.",
  ["dig","break","row","furrow","space","depth","sow","thin","weed","water","seedling","grow"],""),
 ("F04","F","The Growing Year","DIAGRAM",50,2,
  "A circular year with the sun's height at the rim and field tasks around it. Deliberately drawn against solar position, not against any named month.",
  ["spring","summer","autumn","winter","sow","tend","harvest","rest","early","late","frost","rain"],
  "Links to The Woven Year calendar work."),
 ("F05","F","Water For Crops","SCENE",50,2,
  "Contour ditch, swale, check dam, well and lift, and a cutaway of mulch holding moisture in the bed.",
  ["water","ditch","channel","dam","flood","drain","mulch","dry","wet","lift","bucket","level"],""),
 ("F06","F","Harvest","SEQUENCE",55,2,
  "Cutting, binding, stacking, threshing, winnowing in the wind, and grain into a raised granary with a rodent guard.",
  ["cut","sheaf","stack","thresh","winnow","chaff","grain","grind","flour","store","granary","pest"],""),
 ("F07","F","Animals","SCENE",60,2,
  "Herding, penning, milking, shearing, working animals in harness, and a birthing scene. Drawn across several body types so it does not assume one species.",
  ["animal","herd","pen","feed","milk","shear","wool","harness","plough","young","breed","tame"],""),

 # ---------------------------------------------------------------- G MATERIALS
 ("G01","G","Cord & Knots","SEQUENCE",55,1,
  "Fibre sources, retting, stripping, and the reverse-wrap twist shown in enlarged hand detail. Then the knots that matter, each drawn mid-tie and finished.",
  ["fibre","strip","ret","twist","spin","cord","rope","knot","loop","bind","tight","strong"],
  "Reverse-wrap is the single highest-leverage manual skill in the set."),
 ("G02","G","Baskets & Weaving","SEQUENCE",50,2,
  "Coiling and plaiting shown stitch by stitch at large scale, a base started, sides raised, rim finished.",
  ["weave","coil","plait","warp","weft","reed","split","base","side","rim","tight","basket"],""),
 ("G03","G","Cloth","SEQUENCE",60,2,
  "Fibre to thread to cloth: carding, the drop spindle in motion, a warp-weighted loom in elevation with the shed opening, and the finished web cut free.",
  ["fibre","card","spindle","spin","thread","loom","warp","weft","shed","weave","cloth","cut"],""),
 ("G04","G","Hides & Leather","SEQUENCE",55,2,
  "Fleshing, dehairing, brain or bark tanning, stretching on a frame, softening by working, and smoking to set it.",
  ["hide","flesh","hair","soak","tan","bark","brain","stretch","frame","soften","smoke","leather"],""),
 ("G05","G","Wood","SCENE",60,2,
  "Felling with the notch and back cut, splitting with wedges along the grain, shaping, and the joints - mortise, lap, peg - drawn in cutaway.",
  ["tree","fell","notch","split","wedge","grain","plank","carve","joint","mortise","peg","glue"],""),
 ("G06","G","Stone","SEQUENCE",55,2,
  "Knapping shown as a striking sequence with the platform and flake scar enlarged; grinding an edge on a wet stone; dry-stone walling with the courses stepped.",
  ["stone","strike","flake","edge","sharp","grind","wet","polish","wall","course","fit","level"],""),
 ("G07","G","Clay & Pots","SEQUENCE",60,2,
  "Digging and cleaning clay, wedging, coiling a vessel, drying to leather hard, burnishing, and firing in a pit. Deliberately self-referential: this is how you would make more of these plates.",
  ["clay","dig","wash","wedge","coil","shape","dry","fire","pit","glaze","crack","pot"],
  "SELF-REFERENTIAL. Links to the ceramic medium the plate itself is made from."),
 ("G08","G","Hot Fire","SEQUENCE",55,2,
  "Charcoal retort, bellows in section, an updraught kiln and a bloomery shaft in cutaway with the air path drawn as arrows.",
  ["charcoal","retort","bellows","air","draught","kiln","furnace","shaft","hot","glow","slag","fuel"],
  "Existing plate02a charcoal retort. The 02b-02d series lands here."),
 ("G09","G","Metal","SEQUENCE",60,2,
  "Ore recognised in the ground, roasted, smelted to a bloom, the bloom consolidated, then forged, quenched and tempered - with colour of the hot metal called out.",
  ["ore","roast","smelt","bloom","slag","forge","hammer","anvil","quench","temper","hard","soft"],""),

 # ---------------------------------------------------------------- H TOOLS
 ("H01","H","Hand Tools","DIAGRAM",65,1,
  "Tools grouped by what they DO rather than by trade: cut, strike, bore, grip, scrape, dig. Each in side elevation with the hand in place.",
  ["knife","axe","adze","saw","hammer","chisel","drill","awl","file","tongs","handle","edge"],""),
 ("H02","H","Simple Machines","DIAGRAM",50,2,
  "Lever, wheel and axle, pulley, wedge, screw, inclined plane - each shown twice: the bare principle, then a person actually using it to move a load.",
  ["lever","fulcrum","load","wheel","axle","pulley","rope","wedge","screw","ramp","lift","force"],""),
 ("H03","H","Turning","SCENE",50,2,
  "Rotary motion: spindle, hand quern, pole lathe with the treadle and springpole, potter's wheel, drill bow.",
  ["turn","spin","round","axle","bearing","quern","grind","lathe","treadle","bow","fast","slow"],""),
 ("H04","H","Water & Wind","SCENE",50,2,
  "Undershot and overshot wheels in elevation with the water path, a sail mill, and the drive train from wheel to millstone.",
  ["water","wheel","flow","fall","sail","wind","turn","shaft","gear","mill","stone","power"],""),
 ("H05","H","Glass & Lens","SEQUENCE",50,2,
  "Sand, ash and lime melted, gathered, blown and cast; then a blank ground and polished into a lens, with the ray path drawn through it and an image formed.",
  ["sand","ash","lime","melt","glass","blow","cast","grind","polish","lens","light","image"],
  "The lens is already a decided capsule item - this is how a finder makes another."),
 ("H06","H","Writing & Copying","SEQUENCE",55,1,
  "Marking surfaces made: charcoal stick, ink from soot and gum, a reed pen, bark and cloth. Then relief carving inked and pressed - a rubbing taken directly off an engraved plate.",
  ["mark","write","ink","soot","gum","pen","surface","bark","carve","press","rub","copy"],
  "SELF-REFERENTIAL and the most important plate for propagation. Half-etch relief means these plates ARE printing plates."),

 # ---------------------------------------------------------------- I MEASURE
 ("I01","I","Measuring","DIAGRAM",55,1,
  "Body-based units shown against a fixed engraved rule on the plate edge, so a real standard can be recovered. Balance beam for weight, marked vessel for volume.",
  ["length","span","cubit","pace","rule","mark","weight","balance","heavy","light","volume","full"],
  "Engrave a physical reference scale on the plate itself. The plate IS the standard."),
 ("I02","I","The Day","DIAGRAM",45,1,
  "The sun's arc with shadow lengths beneath at each position, a gnomon casting them, and the corresponding activity below.",
  ["sun","rise","noon","set","shadow","long","short","morning","evening","night","dark","light"],""),
 ("I03","I","The Year","DIAGRAM",50,2,
  "Solstice and equinox found by shadow length, the sun's rising point shifting along the horizon, and the year closing as a circle.",
  ["year","season","solstice","equinox","horizon","north","south","longest","shortest","count","repeat","calendar"],
  "Links to The Woven Year and the planisphere work."),
 ("I04","I","Stars","DIAGRAM",55,2,
  "Circumpolar rotation drawn as arcs, the pole found by construction from a named asterism, altitude equals latitude shown with a horizon angle.",
  ["star","night","sky","turn","pole","north","south","cross","rise","set","angle","latitude"],
  "WARNING: the Polaris line on existing plate06 is recorded as WRONG. Fix before reuse. Precession matters over this timescale."),
 ("I05","I","Place & Landscape","SCENE",55,2,
  "A landscape above, the same ground as a plan map below, with the correspondence lines drawn between them - teaching what a map IS before asking anyone to read one.",
  ["map","ground","hill","valley","river","coast","path","far","near","direction","mark","place"],""),
 ("I06","I","Weather","ARRAY",45,2,
  "Cloud forms paired with what follows them, wind shift paired with change, and animal behaviour paired with the coming weather.",
  ["cloud","rain","storm","wind","fog","frost","dry","flood","before","after","sign","expect"],""),

 # ---------------------------------------------------------------- J SOCIETY
 ("J01","J","Working Together","SCENE",50,1,
  "One person failing to move a load; several moving it easily; a task divided into parts along a line of people. Cooperation shown as a mechanical fact first.",
  ["work","help","together","share","turn","part","lift","carry","task","group","alone","enough"],""),
 ("J02","J","Trade & Value","SCENE",55,2,
  "Direct exchange, then a third good used as a measure between two others, then a marked token standing for it. The abstraction of money built up in three steps.",
  ["give","take","trade","exchange","worth","more","less","equal","token","debt","owe","pay"],""),
 ("J03","J","What Is Held In Common","DIAGRAM",55,2,
  "A shared water source and pasture with boundary, users, and rules of access drawn as a bounded diagram. Overuse shown as a consequence sequence beneath.",
  ["common","share","boundary","use","limit","rule","member","outside","overuse","empty","keep","care"],
  "Ostrom series 05A-05I. This is their pictorial entry point."),
 ("J04","J","Promise & Agreement","SEQUENCE",50,2,
  "Two parties, a stated undertaking, a witness present, a mark made on a durable thing, and the two panels that follow: kept, and broken.",
  ["promise","agree","witness","mark","record","keep","break","trust","before","after","true","false"],""),
 ("J05","J","Dispute & Judgment","SEQUENCE",55,2,
  "A conflict, both accounts heard in separate panels, a third party listening, evidence shown, a decision, and restitution made.",
  ["argue","claim","hear","both","witness","evidence","judge","decide","fair","wrong","repay","end"],""),
 ("J06","J","Deciding Together","SEQUENCE",55,2,
  "An assembly: the matter raised, speaking in turn, counting the sides, the decision recorded, and the minority still present afterward.",
  ["meet","speak","turn","listen","count","most","few","decide","record","follow","change","again"],
  "Governance series 05A-05I."),
 ("J07","J","When It Goes Wrong","SEQUENCE",55,2,
  "The corruption sequence drawn as stages: crisis, emergency power, permanence, and at each stage the interruption that stops it. Group-count grammar, not diminished figures.",
  ["power","few","many","fear","take","hold","hide","ask","refuse","open","stop","return"],
  "BLOCKED on the diminished-figure vocabulary problem. Prefer group-count over posture."),

 # ---------------------------------------------------------------- K LANGUAGE
 ("K01","K","Speaking & Naming","SCENE",50,1,
  "Pointing at a thing and saying its name; asking and being answered; a misunderstanding and its repair. The act of naming shown as an act.",
  ["speak","say","name","call","ask","answer","tell","hear","understand","repeat","mean","word"],""),
 ("K02","K","Writing Systems","DIAGRAM",55,2,
  "The same short sentence in several scripts side by side with the sound correspondence marked - alphabet, abjad, syllabary and logograph shown as different solutions to one problem.",
  ["write","letter","sign","sound","script","read","line","direction","left","right","same","different"],
  "Links to plate01 Rosetta index and the 50-language series."),
 ("K03","K","Teaching","SEQUENCE",45,1,
  "Watching, being shown, trying and failing, being corrected, doing it alone, then showing someone else. The transmission loop closed explicitly.",
  ["learn","teach","show","watch","try","fail","again","correct","practise","know","remember","pass on"],""),
 ("K04","K","Feeling","ARRAY",55,1,
  "Faces and whole-body postures paired with the situation that caused them, because posture without context does not translate. Situation on the left, body on the right.",
  ["happy","sad","angry","afraid","calm","tired","hurt","glad","alone","loved","want","enough"],""),
 ("K05","K","Belief & Ritual","SCENE",45,2,
  "Several practices shown side by side without hierarchy: gathering, marking a season, honouring the dead, an oath taken. Deliberately plural.",
  ["believe","holy","gather","song","dance","offer","oath","spirit","ancestor","season","mark","together"],
  "HIGH cultural-assumption risk. Depict the ACT, never the doctrine."),

 # ---------------------------------------------------------------- L ABSTRACT
 ("L01","L","Opposites: Things","ARRAY",65,0,
  "Paired panels, identical but for the one property: big/small stone, hot/cold water with steam and ice, wet/dry cloth, hard/soft, heavy/light on a balance.",
  ["big","small","hot","cold","wet","dry","hard","soft","heavy","light","full","empty","open","shut"],""),
 ("L02","L","Opposites: Judgments","ARRAY",60,0,
  "Value words shown by consequence rather than assertion: the good act and its outcome beside the bad act and its outcome. Never a tick or a cross.",
  ["good","bad","true","false","right","wrong","fair","unfair","kind","cruel","safe","danger"],
  "The hardest plate to draw honestly. Consequence, not symbol."),
 ("L03","L","Where","ARRAY",55,0,
  "One object and one reference, redrawn for each relation: in, on, under, beside, between, inside, behind, above, near, far.",
  ["in","on","under","over","beside","between","inside","outside","behind","near","far","here"],""),
 ("L04","L","Moving","ARRAY",50,0,
  "A figure and a fixed marker, redrawn for each: come, go, up, down, in, out, through, across, around, toward, away, stop.",
  ["come","go","up","down","in","out","through","across","around","toward","away","stop"],""),
 # ---- added on review: gaps found after the first pass ----
 ("A06","A","Light, Dark & Seeing","ARRAY",50,1,
  "The same scene at noon, dusk and by firelight. A shadow cast and its direction traced back to the source. Reflection in still water. What the eye can and cannot resolve at distance.",
  ["light","dark","bright","dim","shadow","shine","reflect","see","look","near","far","blind"],
  "Feeds H05 lens and I02 the day."),
 ("D06","D","Pests & Vermin","SCENE",55,2,
  "Rat, louse, flea, fly, mosquito, worm and weevil drawn at readable scale beside what each spoils or causes, with the exclusion measure alongside - raised store, netting, smoke, boiling.",
  ["rat","mouse","louse","flea","fly","mosquito","worm","weevil","bite","itch","spoil","exclude"],
  "The disease-vector link is the reason this plate exists, not squeamishness."),
 ("E09","E","The Living World: Plants","DIAGRAM",65,2,
  "A naming structure rather than a species list: tree/shrub/herb/grass/vine/moss/fungus, with leaf shape, edge and arrangement called out as the features that let a finder DESCRIBE an unknown plant.",
  ["tree","shrub","herb","grass","vine","moss","fungus","leaf","stem","root","flower","fruit","thorn","sap"],
  "Teach the descriptive vocabulary, not the field guide. Species distributions shift over millennia."),
 ("E10","E","The Living World: Animals","DIAGRAM",65,2,
  "Same approach: body plans grouped - four-legged, winged, finned, many-legged, no-legged - with the parts called out that let an unknown animal be described and its tracks read.",
  ["animal","bird","fish","insect","snake","fur","feather","scale","wing","claw","horn","track","nest","egg"],""),
 ("G10","G","Containers & Vessels","DIAGRAM",60,1,
  "Everything that holds something, grouped by what it must resist: water, weight, vermin, air. Pot, gourd, basket, sack, skin, box, barrel, and the lids and seals for each.",
  ["pot","jar","gourd","basket","sack","skin","box","barrel","lid","stopper","seal","tight","leak","hold"],""),
 ("G11","G","Clothing & Footwear","SEQUENCE",60,1,
  "A garment cut from a hide and from woven cloth, laid flat then worn. Layering for cold in cutaway. A shoe built from sole to upper, and repair at the wear points.",
  ["cloth","cut","sew","needle","thread","seam","coat","shirt","belt","shoe","sole","patch","mend","wear"],""),
 ("H07","H","Boats & Water","SCENE",65,2,
  "Raft, dugout, skin boat and plank hull in cutaway; paddle, oar, pole and sail; how a hull is made watertight; loading and trim; reading current and shallow water.",
  ["boat","raft","hull","keel","plank","caulk","paddle","oar","pole","sail","mast","anchor","float","sink","current","trim"],
  "Cormac is a merchant mariner - this is the plate where his own expertise beats any source. Overlaps G01 for knots and rigging."),
 ("H08","H","Carrying & Hauling","SCENE",55,2,
  "Load on the back, head and shoulder; pack frame; travois; sled on snow; roller and skid; a cart with the axle in cutaway. Each shown against the load it suits.",
  ["carry","load","pack","frame","strap","drag","sled","roller","skid","cart","axle","yoke","push","pull"],""),
 ("I07","I","Colour","ARRAY",50,2,
  "Colour named against real materials that carry it - ochre, charcoal, chalk, indigo, madder, copper - so the word is anchored to a findable substance, not to a printed swatch.",
  ["red","yellow","brown","black","white","green","blue","ochre","charcoal","chalk","dye","stain","fade","bright"],
  "CERAMIC ONLY at full value - titanium cannot halftone. The rule stands: colour may differentiate, never signify."),
 ("I08","I","Working With Number","DIAGRAM",55,2,
  "Operations shown as physical acts on counted objects: combining, taking away, sharing out into equal groups, doubling, halving, and a part of a whole drawn as a divided object.",
  ["add","take away","share","equal","group","double","half","part","whole","more","less","measure","times","left over"],
  "Builds on A05. Mayan dot-bar throughout."),
 ("J08","J","Strangers & Boundaries","SEQUENCE",55,2,
  "Two groups meeting: approach in the open, hands shown empty, goods set down and stepped back from, a boundary marked and respected. Then the panels where it goes wrong, and the repair.",
  ["stranger","meet","approach","open","empty","give","boundary","edge","cross","permit","refuse","peace","fight","repair"],
  "Silent trade is attested independently across unconnected cultures - one of the few genuinely universal protocols."),
 ("K06","K","Sound & Music","DIAGRAM",50,2,
  "A string and a pipe shortened in steps with the pitch change marked, a stretched skin struck, and beats drawn as evenly spaced marks along a line.",
  ["sound","loud","quiet","high","low","string","pipe","drum","pluck","strike","blow","beat","rhythm","song"],
  "Links to plate08 physics of sound and plate09 audio playback."),

 ("L05","L","If, Because, Maybe","SEQUENCE",55,0,
  "Logic drawn as branching panels: one cause and its effect; the same act not done and nothing following; a fork with both outcomes drawn for 'maybe'; all/some/none as counted groups.",
  ["if","then","because","not","maybe","can","all","some","none","same","other","before","after"],
  "NSM primes. The most abstract plate and the one that makes every definition elsewhere possible."),
]


def summary():
    from collections import Counter
    tot = sum(p[4] for p in PLATES)
    print(f"{len(PLATES)} plates, {tot:,} words, {tot/len(PLATES):.1f} avg per plate")
    print(f"two-sided in 120x170mm: {-(-len(PLATES)//2)} physical plates, "
          f"{len(PLATES)*120*170/1e6:.2f} m2")
    print("\nby grammar:", dict(Counter(p[3] for p in PLATES)))
    print("by tier:   ", dict(sorted(Counter(p[5] for p in PLATES).items())))
    print()
    for code, name, blurb in SECTIONS:
        ps = [p for p in PLATES if p[1] == code]
        print(f"  {code}  {name:<24} {len(ps):>2} plates  {sum(x[4] for x in ps):>4} words")


if __name__ == "__main__":
    summary()
